export type BuiltInMusicTrack = {
  id: string;
  title: string;
  artist: string;
  description: string;
  src: string;
};

// These short ambient loops are generated by scripts/generate-ambient-audio.mjs.
// They are original project assets, not links to commercial or third-party music.
export const builtInMusicTracks: BuiltInMusicTrack[] = [
  {
    id: "myne-quiet-drift",
    title: "Quiet Drift",
    artist: "Myne Originals",
    description: "A slow, warm ambient loop for quiet reading.",
    src: "/audio/quiet-drift.wav",
  },
  {
    id: "myne-lantern-rain",
    title: "Lantern Rain",
    artist: "Myne Originals",
    description: "A soft, shimmering ambient loop for long chapters.",
    src: "/audio/lantern-rain.wav",
  },
];
