"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { BookCard } from "@/components/book-card";
import { BookReviews } from "@/components/book-reviews";
import { Icon } from "@/components/icons";
import { useI18n } from "@/components/language-provider";
import { Shell } from "@/components/shell";
import { syncFavoriteBookIds } from "@/lib/favorites";
import { getLibrary, libraryKey, saveLibrary, saveRecentlyViewed } from "@/lib/storage";
import { authorNames, catalogueMetadata, coverUrl, epubUrl, type Author, type Book, type BookSet, type CatalogueMetadata } from "@/types/book";

type BookDetailsProps = { id: string };
type ActionState = "favorite" | "save" | "share" | "wishlist" | null;
type Notice = { kind: "error" | "status"; text: string } | null;
type Translate = ReturnType<typeof useI18n>["t"];

function isBook(value: unknown): value is Book {
  if (!value || typeof value !== "object") return false;
  const book = value as Partial<Book>;
  return typeof book.id === "number" && typeof book.title === "string" && Array.isArray(book.authors) && Array.isArray(book.subjects) && Array.isArray(book.bookshelves) && Array.isArray(book.languages) && typeof book.formats === "object" && book.formats !== null;
}
function isBookSet(value: unknown): value is BookSet { return Boolean(value && typeof value === "object" && Array.isArray((value as Partial<BookSet>).results) && (value as Partial<BookSet>).results?.every(isBook)); }
async function responseError(response: Response, fallback: string) { const data: unknown = await response.json().catch(() => null); return data && typeof data === "object" && "error" in data && typeof data.error === "string" ? data.error : fallback; }

function BookMetadata({ book, metadata, t }: { book: Book; metadata: CatalogueMetadata; t: Translate }) {
  return <><p className="eyebrow">{metadata.status} · {metadata.genre}</p><h1>{book.title}</h1><p className="book-detail-author">{authorNames(book)}</p>
    <div className="book-detail-facts"><span><small>{t("book.language")}</small>{book.languages.join(", ").toUpperCase() || t("book.unavailable")}</span><span><small>Genre</small>{metadata.genre}</span><span><small>Publication</small>{metadata.publicationDate}</span><span><small>Reader rating</small>★ {metadata.rating} · {metadata.reviewCount} reviews</span><span><small>Reading time</small>{metadata.readingTime}</span><span><small>Price</small>{metadata.price} · {metadata.status}</span></div>
    <section className="book-synopsis"><h2>{t("book.synopsis")}</h2><p>{book.summaries?.[0] || book.subjects.slice(0, 5).join(" · ") || t("book.synopsisFallback")}</p></section></>;
}

function BookActions({ action, book, favorite, metadata, wishlisted, saved, onSave, onFavorite, onWishlist, onShare, t }: { action: ActionState; book: Book; favorite: boolean; metadata: CatalogueMetadata; wishlisted: boolean; saved: boolean; onSave: (open?: boolean) => void; onFavorite: () => void; onWishlist: () => void; onShare: () => void; t: Translate }) {
  const saving = action === "save"; const downloadable = Boolean(epubUrl(book)); const purchaseText = metadata.status === "Free" ? "Free download" : `Purchase · ${metadata.price}`;
  return <div className="book-detail-actions">
    {saved ? <Link className="primary-button" href={`/reader/${encodeURIComponent(libraryKey(book.id))}`}>Preview / read <Icon name="chevron-right" size={18} /></Link> : <button className="primary-button" disabled={!downloadable || saving} onClick={() => onSave(true)} type="button">{saving ? t("book.downloading") : "Preview"} <Icon name="chevron-right" size={18} /></button>}
    <button className="outline-button" disabled={!downloadable || saving || saved} onClick={() => onSave()} type="button"><Icon name="download" size={18} />{saved ? "In your library" : saving ? t("book.downloading") : "Add to library"}</button>
    <button className="purchase-button" disabled={!downloadable || saving || saved} onClick={() => onSave()} type="button">{saved ? "In your library" : purchaseText}</button>
    <button className="outline-button" disabled={action === "wishlist"} onClick={onWishlist} type="button"><Icon name="star" size={18} />{wishlisted ? t("book.wishlistRemove") : t("book.wishlistAdd")}</button>
    <button aria-label={t("book.favoriteAria")} aria-pressed={favorite} className={favorite ? "icon-action active" : "icon-action"} disabled={action === "favorite"} onClick={onFavorite} type="button"><Icon name="heart" size={19} /></button><button aria-label={t("book.shareAria")} className="icon-action" disabled={action === "share"} onClick={onShare} type="button"><Icon name="share" size={19} /></button>
  </div>;
}

function AuthorSection({ author, books }: { author?: Author; books: Book[] }) {
  const life = author ? [author.birth_year, author.death_year].filter((year): year is number => typeof year === "number").join("–") : "";
  return <section className="author-profile"><p className="eyebrow">About the author</p><h2>{author?.name || "Unknown author"}</h2><h3>Biography</h3><p>{author ? `${author.name}${life ? ` (${life})` : ""} is represented in the Myne public-domain collection. Explore their available writing and save a title to continue reading anywhere in this browser.` : "Author information is not available for this edition."}</p>{books.length > 0 && <><h3>More by {author?.name}</h3><div className="related-book-grid">{books.map((item) => <BookCard book={item} key={item.id} />)}</div></>}</section>;
}
function RelatedBooks({ books, failed }: { books: Book[]; failed: boolean }) { return <section className="similar-books"><div className="section-heading"><div><p className="eyebrow">Keep discovering</p><h2>Similar books</h2></div></div>{books.length ? <div className="related-book-grid">{books.map((item) => <BookCard book={item} key={item.id} />)}</div> : <p className="related-loading">{failed ? "Related books are unavailable right now." : "Finding related books…"}</p>}</section>; }

export function BookDetails({ id }: BookDetailsProps) {
  const { profile, refreshProfile, setWishlistBook, user } = useAuth(); const { t } = useI18n(); const router = useRouter(); const mounted = useRef(true);
  const [book, setBook] = useState<Book | null>(null); const [favorite, setFavorite] = useState(false); const [saved, setSaved] = useState(false); const [authorBooks, setAuthorBooks] = useState<Book[]>([]); const [similarBooks, setSimilarBooks] = useState<Book[]>([]); const [relatedFailed, setRelatedFailed] = useState(false); const [notice, setNotice] = useState<Notice>(null); const [action, setAction] = useState<ActionState>(null);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);

  useEffect(() => { const controller = new AbortController(); setBook(null); setNotice(null); setAuthorBooks([]); setSimilarBooks([]); setRelatedFailed(false); void (async () => { try { const response = await fetch(`/api/books?ids=${encodeURIComponent(id)}`, { signal: controller.signal }); if (!response.ok) throw new Error(await responseError(response, t("book.detailUnavailable"))); const payload: unknown = await response.json(); if (!isBookSet(payload) || !payload.results[0]) throw new Error(t("book.detailUnavailable")); const next = payload.results[0]; if (!mounted.current) return; setBook(next); try { await saveRecentlyViewed({ authors: authorNames(next), cover: coverUrl(next), key: libraryKey(next.id), title: next.title, viewedAt: Date.now() }); } catch { if (mounted.current) setNotice({ kind: "status", text: "Book opened, but recently viewed history could not be saved." }); } } catch (reason) { if (!controller.signal.aborted && mounted.current) setNotice({ kind: "error", text: reason instanceof Error ? reason.message : t("book.detailUnavailable") }); } })(); return () => controller.abort(); }, [id, t]);
  useEffect(() => { const bookId = Number(id); if (!Number.isSafeInteger(bookId)) { setSaved(false); setFavorite(false); return; } let cancelled = false; void getLibrary(libraryKey(bookId)).then((entry) => { if (!cancelled) { setSaved(Boolean(entry)); setFavorite(Boolean(entry?.favorite)); } }).catch(() => { if (!cancelled) setNotice({ kind: "error", text: "Your local library could not be opened." }); }); return () => { cancelled = true; }; }, [id]);
  useEffect(() => { if (!book) return; const controller = new AbortController(); const author = book.authors[0]?.name; const topic = book.bookshelves[0] || book.subjects[0] || "fiction"; void (async () => { try { const [authorResponse, similarResponse] = await Promise.all([author ? fetch(`/api/books?${new URLSearchParams({ search: author })}`, { signal: controller.signal }) : Promise.resolve(null), fetch(`/api/books?${new URLSearchParams({ topic })}`, { signal: controller.signal })]); const [authorPayload, similarPayload]: unknown[] = await Promise.all([authorResponse?.ok ? authorResponse.json() : Promise.resolve(null), similarResponse.ok ? similarResponse.json() : Promise.resolve(null)]); if (controller.signal.aborted || !mounted.current) return; setAuthorBooks(isBookSet(authorPayload) ? authorPayload.results.filter((item) => item.id !== book.id).slice(0, 3) : []); setSimilarBooks(isBookSet(similarPayload) ? similarPayload.results.filter((item) => item.id !== book.id).slice(0, 4) : []); setRelatedFailed(!similarResponse.ok || !isBookSet(similarPayload)); } catch { if (!controller.signal.aborted && mounted.current) { setAuthorBooks([]); setSimilarBooks([]); setRelatedFailed(true); } } })(); return () => controller.abort(); }, [book]);

  const saveBook = useCallback(async (open = false) => { if (!book || action) return; const remote = epubUrl(book); if (!remote) { setNotice({ kind: "error", text: t("book.epubMissing") }); return; } setAction("save"); setNotice({ kind: "status", text: t("book.downloading") }); try { const response = await fetch(`/api/epub?url=${encodeURIComponent(remote)}`); if (!response.ok) throw new Error(await responseError(response, t("book.saveError"))); const blob = await response.blob(); if (!blob.size) throw new Error(t("book.saveError")); const key = libraryKey(book.id); const old = await getLibrary(key); await saveLibrary({ addedAt: old?.addedAt || Date.now(), authors: authorNames(book), blob, book, cover: coverUrl(book), favorite: old?.favorite || false, imported: false, key, title: book.title }); if (!mounted.current) return; setFavorite(old?.favorite || false); setSaved(true); setNotice({ kind: "status", text: t("book.saved") }); try { await refreshProfile(); } catch { setNotice({ kind: "status", text: "Book saved locally. Firebase profile sync is unavailable right now." }); } if (open) router.push(`/reader/${encodeURIComponent(key)}`); } catch (reason) { if (mounted.current) setNotice({ kind: "error", text: reason instanceof Error ? reason.message : t("book.saveError") }); } finally { if (mounted.current) setAction(null); } }, [action, book, refreshProfile, router, t]);
  const toggleFavorite = useCallback(async () => { if (!book || action) return; setAction("favorite"); try { const entry = await getLibrary(libraryKey(book.id)); if (!entry) { setNotice({ kind: "status", text: t("book.downloadFirst") }); return; } const updated = { ...entry, favorite: !entry.favorite }; await saveLibrary(updated); if (!mounted.current) return; setFavorite(updated.favorite); try { await refreshProfile(); } catch { setNotice({ kind: "status", text: "Favorite saved locally. Firebase profile sync is unavailable right now." }); } try { const synced = await syncFavoriteBookIds(); if (mounted.current) setNotice({ kind: "status", text: synced ? t("book.favoriteSynced") : t("book.favoriteBrowser") }); } catch { if (mounted.current) setNotice({ kind: "status", text: t("book.favoriteFirebaseDenied") }); } } catch (reason) { if (mounted.current) setNotice({ kind: "error", text: reason instanceof Error ? reason.message : t("book.saveError") }); } finally { if (mounted.current) setAction(null); } }, [action, book, refreshProfile, t]);
  const shareBook = useCallback(async () => { if (!book || action) return; setAction("share"); try { const url = `${window.location.origin}/book/${book.id}`; const nativeShare = (navigator as { share?: (data: ShareData) => Promise<void> }).share; if (nativeShare) await nativeShare.call(navigator, { text: t("book.shareText", { author: authorNames(book), title: book.title }), title: book.title, url }); else if (navigator.clipboard) await navigator.clipboard.writeText(url); else throw new Error(t("library.shareNoMethod")); if (mounted.current) setNotice({ kind: "status", text: nativeShare ? t("book.bookLinkShared") : t("book.bookLinkCopied") }); } catch (reason) { if (!(reason instanceof DOMException && reason.name === "AbortError") && mounted.current) setNotice({ kind: "error", text: reason instanceof Error ? reason.message : t("book.bookLinkShareError") }); } finally { if (mounted.current) setAction(null); } }, [action, book, t]);
  const toggleWishlist = useCallback(async () => { if (!book || action) return; if (!user) { setNotice({ kind: "status", text: t("book.wishlistLogin") }); return; } setAction("wishlist"); try { await setWishlistBook(book.id, !profile?.wishlistBookIds.includes(book.id)); if (mounted.current) setNotice({ kind: "status", text: t("book.wishlistSaved") }); } catch (reason) { if (mounted.current) setNotice({ kind: "error", text: reason instanceof Error ? reason.message.replace("Firebase: ", "") : t("book.wishlistLogin") }); } finally { if (mounted.current) setAction(null); } }, [action, book, profile?.wishlistBookIds, setWishlistBook, t, user]);
  const metadata = useMemo(() => book ? catalogueMetadata(book) : null, [book]); const wishlisted = Boolean(book && profile?.wishlistBookIds.includes(book.id));
  return <Shell>{notice && <div className={`notice ${notice.kind === "error" ? "error" : ""}`}>{notice.text}</div>}{!book ? <div className="loading-card">{notice?.kind === "error" ? t("book.detailUnavailable") : t("book.loading")}</div> : metadata && <article className="book-detail-page"><div className="book-detail-cover-column"><div className="book-detail-cover"><Image alt={t("book.coverAlt", { title: book.title })} fill priority sizes="(max-width: 760px) 78vw, 360px" src={coverUrl(book)} unoptimized /></div><p>{t("book.gutenbergId", { id: book.id })}</p></div><div className="book-detail-content"><BookMetadata book={book} metadata={metadata} t={t} /><BookActions action={action} book={book} favorite={favorite} metadata={metadata} onFavorite={() => void toggleFavorite()} onSave={(open) => void saveBook(open)} onShare={() => void shareBook()} onWishlist={() => void toggleWishlist()} saved={saved} t={t} wishlisted={wishlisted} /><p className="detail-action-note">{t("book.localNote")}</p>{notice?.kind === "status" && <p className="status-message" role="status">{notice.text}</p>}<section className="book-subjects"><h2>{t("book.subjects")}</h2><div>{book.subjects.length ? book.subjects.map((subject) => <span key={subject}>{subject}</span>) : <span>{t("book.subjectsEmpty")}</span>}</div></section><BookReviews bookId={book.id} /><AuthorSection author={book.authors[0]} books={authorBooks} /><RelatedBooks books={similarBooks} failed={relatedFailed} /></div></article>}</Shell>;
}
